name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  FORCE_COLOR: 3
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  BORING_STACK_TOKEN: ${{ secrets.BORING_STACK_TOKEN }}

jobs:
  get-features:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    outputs:
      features: ${{ steps.list-features.outputs.features }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: ./tooling/github/setup

      - name: List optional features
        id: list-features
        run: |
          FEATURES_MATRIX=$(./scripts/get-features-combinations.sh)
          echo "features=$FEATURES_MATRIX" >> $GITHUB_OUTPUT

  lint:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    needs: get-features
    strategy:
      matrix:
        features: ${{ fromJSON(needs.get-features.outputs.features) }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: ./tooling/github/setup

      - name: Copy env
        shell: bash
        run: cp .env.example .env

      - name: Install features
        run: ./scripts/install-features.sh '${{ toJSON(matrix.features) }}'
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Build internal packages
        run: pnpm build --filter='./packages/*'

      - name: Lint
        run: pnpm lint && pnpm lint:ws

  format:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    needs: get-features
    strategy:
      matrix:
        features: ${{ fromJSON(needs.get-features.outputs.features) }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: ./tooling/github/setup

      - name: Copy env
        shell: bash
        run: cp .env.example .env

      - name: Install features
        run: ./scripts/install-features.sh '${{ toJSON(matrix.features) }}'
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Format
        run: pnpm format

  typecheck:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    needs: get-features
    strategy:
      matrix:
        features: ${{ fromJSON(needs.get-features.outputs.features) }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: ./tooling/github/setup

      - name: Copy env
        shell: bash
        run: cp .env.example .env

      - name: Install features
        run: ./scripts/install-features.sh '${{ toJSON(matrix.features) }}'
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Build internal packages
        run: pnpm build --filter='./packages/*'

      - name: Typecheck
        run: pnpm typecheck

  test:
    name: Test
    needs: get-features
    timeout-minutes: 15
    runs-on: blacksmith-4vcpu-ubuntu-2404
    strategy:
      matrix:
        features: ${{ fromJSON(needs.get-features.outputs.features) }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: ./tooling/github/setup

      - name: Install features
        run: ./scripts/install-features.sh '${{ toJSON(matrix.features) }}'
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Start supabase
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase start
        run: supabase start -x studio,vector,inbucket,realtime

      - name: Update repositories
        run: sudo apt-get update

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Reset DB
        run: pnpm db:reset

      - name: Run Playwright tests
        run: turbo e2e test

      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: playwright-report
          path: e2e/playwright-report/${{ join(matrix.features, '') }}
          retention-days: 30
